using OpenQA.Selenium;using OpenQA.Selenium.Chrome;using OpenQA.Selenium.Interactions;using OpenQA.Selenium.Support.UI;using System;using System.Collections.Generic;using System.Linq;using System.Text;using System.Threading;using System.Threading.Tasks;using Microsoft.Office.Interop.Excel;using _Excel = Microsoft.Office.Interop.Excel;using System.IO;using OfficeOpenXml;namespace flipkartBot{    class Program    {        private static int pg;                                     static void Main(string[] args)        {            string fileName = "test.xlsx";            string paths = "C:/halitha/flipkart/" + fileName;            FileInfo file = new FileInfo(paths);            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;            ExcelPackage pck = new ExcelPackage(file);
                        ExcelWorksheet ws = pck.Workbook.Worksheets.Add("WatchName");            ws.Cells[1, 1].Value = "WatchName";
            ws.Cells[1, 2].Value = "WatchPrice";

            // IWebDriver driver1 = new ChromeDriver(@"C:\halitha\chromedriver");
            using (var driver1 = new ChromeDriver(@"C:\halitha\chromedriver"))            {                driver1.Navigate().GoToUrl("https://www.flipkart.com/");                              for (int pg = 1; pg < 5; pg++)                {                    driver1.Navigate().GoToUrl("https://www.flipkart.com/search?q=watches&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=" + pg);                                          List<IWebElement> watchName = driver1.FindElements(By.ClassName("_2WkVRV")).ToList();  //name  //_1vC4OE price                     List<IWebElement> watchPrice = driver1.FindElements(By.ClassName("_30jeq3")).ToList();                    for (int i = 0; i < watchName.Count; i++)                    {

                        Console.WriteLine("Watch name :" + watchName[i].Text);                         Console.WriteLine("price : " + watchPrice[i].Text);                        var details = "Watch name :" + watchName[i].Text;
                        var price = "watchPrice:" + watchPrice[i].Text;                        int lastRow = ws.Dimension.End.Row;                        //var test = lastRow;                        ws.Cells["A" + (lastRow + 1)].Value = details;                        ws.Cells["B" + (lastRow + 1)].Value = price;                        ws.Cells.AutoFitColumns();
                                            pck.Save();                                       }                  //  StreamWriter sw = new StreamWriter("C:/halitha/flipkart/"+"test.xlsx");                }            }            //while (true)  logic for next scenaio button            //{            //  bool arrowisPresent = driver1.FindElement(By.XPath("/html/body/div[1]/div/div[3]/div[2]/div[1]/div[2]/div[12]/div/div/nav/a[11]/span")).Displayed;            //  if (arrowisPresent ==true)            //  {            //  }            //}            //WebDriver driver = new FirefoxDriver();  logic for infinite page scrolling            //JavascriptExecutor jse = (JavascriptExecutor)driver;            //jse.executeScript("window.scrollBy(0,250)");        }    }}